# Generated by Django 4.1.3 on 2022-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdoctor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
