# Generated by Django 4.1.5 on 2023-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_appointments_doctor_alter_appointments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
