# Generated by Django 4.1.5 on 2023-01-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_appointments_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='file',
            new_name='medical_file',
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
