# Generated by Django 4.1.5 on 2023-01-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_file_appointments_medical_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='medical_file',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='payment_file',
        ),
    ]
