# Generated by Django 4.1.5 on 2023-01-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_appointments_medical_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_file', models.FileField(blank=True, null=True, upload_to='')),
                ('medical_file', models.FileField(blank=True, null=True, upload_to='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.appointments')),
            ],
        ),
    ]
