# Generated by Django 4.1.5 on 2023-01-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
