# Generated by Django 4.1.5 on 2023-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_document_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient_payment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
