# Generated by Django 4.1.5 on 2023-01-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_payment_patient_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
