# Generated by Django 4.1.5 on 2023-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient_payment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
