# Generated by Django 4.1.5 on 2023-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_appointments_patient_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.DeleteModel(
            name='Upload_file',
        ),
    ]
