# Generated by Django 4.1.5 on 2023-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_appointments_medical_file_appointments_payment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoctor',
            name='rate',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
