# Generated by Django 4.1.5 on 2023-01-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_messege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege',
            name='secretary',
        ),
    ]
