# Generated by Django 4.1.5 on 2023-01-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_messege_secretary'),
    ]

    operations = [
        migrations.CreateModel(
            name='messegetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.userdoctor')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usersecretary')),
            ],
        ),
    ]
