# Generated by Django 4.1.5 on 2023-01-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_messegetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='messege_for_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.userpatient')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usersecretary')),
            ],
        ),
    ]
